//auth Action Types
// Create
export const SERVICE_CREATION_STARTED = "SERVICE_CREATION_STARTED";
export const SERVICE_CREATION_SUCCES = "SERVICE_CREATION_SUCCES";
export const SERVICE_CREATION_FAIL = "SERVICE_CREATION_FAIL";

//SERVICE details
export const SERVICE_DETAILS_STARTED = "SERVICE_DETAILS_STARTED";
export const SERVICE_DETAILS_SUCCESS = "SERVICE_DETAILS_SUCCESS";
export const SERVICE_DETAILS_FAIL = "SERVICE_DETAILS_FAIL";

//Fetch
export const SERVICE_FETCH_STARTED = "SERVICE_FETCH_STARTED";
export const SERVICE_FETCH_SUCCES = "SERVICE_FETCH_SUCCES";
export const SERVICE_FETCH_FAIL = "SERVICE_FETCH_FAIL";

//Update
export const SERVICE_UPDATE_STARTED = "SERVICE_UPDATE_STARTED";
export const SERVICE_UPDATE_SUCCES = "SERVICE_UPDATE_SUCCES";
export const SERVICE_UPDATE_FAIL = "SERVICE_UPDATE_FAIL";

//Delete
export const SERVICE_DELETE_STARTED = "SERVICE_DELETE_STARTED";
export const SERVICE_DELETE_SUCCES = "SERVICE_DELETE_SUCCES";
export const SERVICE_DELETE_FAIL = "SERVICE_DELETE_FAIL";
